lib/mango_web/router.ex
defmodule MangoWeb.Router do
  use MangoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MangoWeb.Plugs.LoadCustomer
    plug MangoWeb.Plugs.FetchCart
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MangoWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/categories/:name", CategoryController, :show
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete
    post "/cart", CartController, :add
    get "/cart", CartController, :show
    put "/cart", CartController, :update
  end

  # Other scopes may use custom stacks.
  # scope "/api", MangoWeb do
  #   pipe_through :api
  # end
end

lib/mango_web/views/layout_view.ex
defmodule MangoWeb.LayoutView do
  use MangoWeb, :view
  import MangoWeb.CartView, only: [cart_count: 1]

  def cart_link_text(conn) do
    raw("""
    <i class="fa fa-shopping-cart"></i> <span class="cartcount">#{cart_count(conn)}</span>
    """)
  end
end

lib/mango_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="Mango Shop">
    <meta name="author" content="shankardevy/sophiabrandt">

    <title>Mango Shop</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <%= render "app_nav.html", conn: @conn, customer: @current_customer  %>
    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        <main role="main">
          <%= render @view_module, @view_template, assigns %>
        </main>
      </div>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/mango_web/templates/layout/app_nav.html.eex
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#"><img src="/images/logo.png"> Mango</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#primary-nav" aria-controls="primary-nav-markup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="primary-nav">
      <ul class="nav navbar-nav">
        <li class="nav-item nav-link"><%= link "Fruits", to: Routes.category_path(@conn, :show, "fruits") %></li>
        <li class="nav-item nav-link"><%= link "Vegetables", to: Routes.category_path(@conn, :show, "vegetables") %></li>
      </ul>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link cart_link_text(@conn), to: Routes.cart_path(@conn, :show), class: "cart nav-link" %></li>
      <%= if @customer do %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle btn btn-secondary" data-toggle="dropdown" role="button"><%= @customer.name %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link "Log Out", to: "/logout" %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link "Register", to: Routes.registration_path(@conn, :new), class: "nav-link" %></li>
        <li><%= link "Sign in", to: Routes.session_path(@conn, :new), class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>